FROM node:9.11.1-alpine as build-stage

RUN mkdir /react-client

WORKDIR ./react-client

COPY package*.json ./

RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && npm install \
    && apk del build-dependencies

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.13.12-alpine as production-stage

RUN mkdir -p /var/www/html/

COPY --from=build-stage /react-client/build /var/www/html/

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./nginx.vh.default.conf /etc/nginx/nginx.vh.default.conf

STOPSIGNAL SIGTERM

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
