export default {
    //-------USERS--------
    USERS: 'USERS',
    USERS_RESPONSE: 'USERS_RESPONSE',

    USER_BY_ID: 'USER_BY_ID',
    USER_BY_ID_RESPONSE: 'USER_BY_ID_RESPONSE',

    USER_CREATE: 'USER_CREATE',
    USER_CREATE_RESPONSE: 'USER_CREATE_RESPONSE',

    USER_UPDATE: 'USER_UPDATE',
    USER_UPDATE_RESPONSE: 'USER_UPDATE_RESPONSE',

    USER_DELETE: 'USER_DELETE',
    USER_DELETE_RESPONSE: 'USER_DELETE_RESPONSE',

    USER_UPLOAD_AVATAR: 'USER_UPLOAD_AVATAR',
    USER_UPLOAD_AVATAR_RESPONSE: 'USER_UPLOAD_AVATAR_RESPONSE',

    USER_REQUEST: 'USER_REQUEST',
    USER_ERROR: 'USER_ERROR',

    //----
    USER_STATE_CHANGE: 'USER_STATE_CHANGE',

    //-------AUTH--------
    LOGIN: 'LOGIN',
    LOGIN_RESPONSE: 'LOGIN_RESPONSE',

    SIGNUP: 'SIGNUP',
    SIGNUP_RESPONSE: 'SIGNUP_RESPONSE',

    LOGOUT: 'LOGOUT',
    LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',

    CUR_USER: 'CUR_USER',
    CUR_USER_RESPONSE: 'CUR_USER_RESPONSE',

    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_ERROR: 'AUTH_ERROR',

    //-------PHOTO--------
    PHOTOS: 'PHOTOS',
    PHOTOS_RESPONSE: 'PHOTOS_RESPONSE',

    PHOTO_BY_ID: 'PHOTO_BY_ID',
    PHOTO_BY_ID_RESPONSE: 'PHOTO_BY_ID_RESPONSE',

    PHOTO_DELETE: 'PHOTO_DELETE',
    PHOTO_DELETE_RESPONSE: 'PHOTO_DELETE_RESPONSE',

    PHOTO_UPLOAD: 'PHOTO_UPLOAD',
    PHOTO_UPLOAD_RESPONSE: 'PHOTO_UPLOAD_RESPONSE',

    PHOTO_REQUEST: 'PHOTO_REQUEST',
    PHOTO_ERROR: 'PHOTO_ERROR',

    //-----COMMENT------

    COMMENTS: 'COMMENTS',
    COMMENTS_RESPONSE: 'COMMENTS_RESPONSE',

    COMMENT_ADD: 'COMMENT_ADD',
    COMMENT_ADD_RESPONSE: 'COMMENT_ADD_RESPONSE',

    COMMENT_EDIT: 'COMMENT_EDIT',
    COMMENT_EDIT_RESPONSE: 'COMMENT_EDIT_RESPONSE',

    COMMENT_DELETE: 'COMMENT_DELETE',
    COMMENT_DELETE_RESPONSE: 'COMMENT_DELETE_RESPONSE',

    COMMENT_REQUEST: 'COMMENT_REQUEST',
    COMMENT_ERROR: 'COMMENT_ERROR',

    //-----ADVERT-----

    ADVERTS: 'ADVERTS',
    ADVERTS_RESPONSE: 'ADVERTS_RESPONSE',

    ADVERT_BY_USER_ID: 'ADVERT_BY_USER_ID',
    ADVERT_BY_USER_ID_RESPONSE: 'ADVERT_BY_USER_ID_RESPONSE',

    ADVERT_BY_ID: 'ADVERT_BY_ID',
    ADVERT_BY_ID_RESPONSE: 'ADVERT_BY_ID_RESPONSE',

    ADVERTS_ADD: 'ADVERTS_ADD',
    ADVERTS_ADD_RESPONSE: 'ADVERTS_ADD_RESPONSE',

    ADVERT_UPDATE: 'ADVERT_UPDATE',
    ADVERT_UPDATE_RESPONSE: 'ADVERT_UPDATE_RESPONSE',

    ADVERT_DELETE: 'ADVERT_DELETE',
    ADVERT_DELETE_RESPONSE: 'ADVERT_DELETE_RESPONSE',

    ADVERTS_REQUEST: 'ADVERTS_REQUEST',
    ADVERTS_ERROR: 'ADVERTS_ERROR',

    //-----CHAT-----
    CONVERSATIONS: 'CONVERSATIONS',
    CONVERSATIONS_RESPONSE: 'CONVERSATIONS_RESPONSE',

    CONVERSATION_BY_ID: 'CONVERSATION_BY_ID',
    CONVERSATION_BY_ID_RESPONSE: 'CONVERSATION_BY_ID_RESPONSE',

    CONVERSATION_CREATE: 'CONVERSATION_CREATE',
    CONVERSATION_CREATE_RESPONSE: 'CONVERSATION_CREATE_RESPONSE',

    CONVERSATION_OPEN: 'CONVERSATION_OPEN',
    CONVERSATION_OPEN_RESPONSE: 'CONVERSATION_OPEN_RESPONSE',

    MESSAGE_CREATE: 'MESSAGE_CREATE',
    MESSAGE_CREATE_RESPONSE: 'MESSAGE_CREATE_RESPONSE',

    CONVERSATIONS_REQUEST: 'CONVERSATIONS_REQUEST',
    CONVERSATIONS_ERROR: 'CONVERSATIONS_ERROR',

    ADD_MESSAGE: 'ADD_MESSAGE',
    ADD_CONVERSATION: 'ADD_CONVERSATION',

    CHANGE_CHAT_STATE: 'CHANGE_CHAT_STATE',
    MESSAGE_TEXT_CHANGE: 'MESSAGE_TEXT_CHANGE',

    //-----SECRET_CHAT-----
    SECRET_CONVERSATIONS_RESPONSE: 'SECRET_CONVERSATIONS_RESPONSE',
    SECRET_CONVERSATION_BY_ID_RESPONSE: 'SECRET_CONVERSATION_BY_ID_RESPONSE',

    ADD_SECRET_MESSAGE: 'ADD_SECRET_MESSAGE',
    ADD_SECRET_CONVERSATION: 'ADD_SECRET_CONVERSATION',
}
